### ISSUE TITLE
Forced login for all pages even public.

### ISSUE THREAD

**Issue by eekbah** [cmcgee93/wp-login-with-twitch#4]
### Expected Functionality 

Being able to view public pages without the need to login.

### Actual Funcationality

Currently, after installing wp-login-with-twitch, all of my pages are set to public and all of them have "default" set in the login with twitch setting. Even with this no matter what page you try to go to, whether it is the main page or any post, it asks for you to be logged in.

### Steps to Reproduce Issue 

Visit any page on my site. https://eekbah.ca/
tested with multiple browsers as well

**Comment by cmcgee93** [comment]
Hey, 

Thanks for using the plugin, please keep in mind this is a bit of a hobby project and it doesn't quite have all the features I was hoping to make just yet. 

I have fixed that issue, thank you for pointing that out. It looks like I had left an old meta key in by mistake which prevented the page redirect from working. I have made a 0.6.1 release, this should fix all of your issues with the page redirects. 

Please let me know if there are any other issues or if there are any feature suggestions. 

**0.6.1 Release**: https://github.com/cmcgee93/wp-login-with-twitch/releases/tag/0.6.1

**Comment by eekbah** [comment]
Thank you so much for the quick reply. I appreciate that you take the time to work on this and am in no rush for answers as my page is far from being ready.

I am not sure I explained properly as the fix didn't change the issue.

I would like visitors to be able to see the site without needing to login. They should only be asked to login once they click to do so or try to visit a page that requires it. Maybe I have done something wrong that is making the plugin direct people to the login screen when accessing the site?

With plugin disabled visiting the site shows you the main page which is just a normal wordpress page with some text.

With plugin enabled visiting the site immediately directs you to the admin login page even though the page should be public and visible to anyone without needing to be logged in.

**Comment by cmcgee93** [comment]
Hi again, 

Ah sorry about that, it looks like I've mixed the two bugs up. Coincidentally I found a bug in the way page access was set and mixed the two up. I've sorted that for you now. 

The check was strict making sure a user is logged in which looking at it was way too agressive for validation. I've changed this now so that only pages you have set to Followers/Subscribers or Followers & Subscibers will require a login. 

I am debating rewriting this plugin as a bit of a cleanup, if I go ahead with this I will try to maintain as much compatibility with earlier versions of the plugin. 

https://github.com/cmcgee93/wp-login-with-twitch/releases/tag/0.6.2

**Comment by eekbah** [comment]
Thank you again for the quick response! This did indeed fix the issue I brought up.

Unfortunately I think there is another issue unrelated to the first. When logging in it creates a user and enters all the proper information such as nickname, email, website, etc... but this user is 100% a follower(it's my bots account) and in their account in wordpress it says they are not. I am wondering if this is due to Twitch's new API system? Should I create a new issue?

Either way this plugin is still saving me a ton of time because I don't plan on actually using the follow/sub restrictions and will actually just be using it to verify their twitch account, use WP to check if they are simply logged in or not, then pull any info I need from my bots database. So, again no rush from me.

**Comment by cmcgee93** [comment]
Hi There, 

Sorry about the delay on this one. I have been rather busy recently, Hopefully the update I have just commited will fix the issues for you, I have not had chance to fully test the subscription side of things, however in theory that should all be working too. 

I am still hoping to do a bit of a rewrite on this plugin and possibly simplify the plugin and allow for features to be toggled on/off on a per site basis rather than having things automatically enabled. I am also hoping to have filters/hooks potentially so that if you are willing to write custom code, you can create your own functionality with less effort. 

Please let me know if there are any issues remaining (Any user currently signed up will be automatically corrected on their next login). I could really do with implementing a feature which resyncs this without requiring the user to log back in, I was making this as more of a proof of concept/testing plugin.
